[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 4321
  publish = "dist"

[context.deploy-preview.environment]
  ENABLE_INTRO_BRIDGE = "true"

[context.branch-deploy.environment]
  ENABLE_INTRO_BRIDGE = "true"
